// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProveeduriaGanadera.Infrastructure.Persistence;

#nullable disable

namespace ProveeduriaGanadera.Infrastructure.Migrations
{
    [DbContext(typeof(ProveeduriaGanaderaDbContext))]
    [Migration("20260924162046_AgregarImagenProducto")]
    partial class AgregarImagenProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClienteUsuario", b =>
                {
                    b.Property<int>("ClientesId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("ClientesId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuarioCliente", (string)null);
                });

            modelBuilder.Entity("EspecieProducto", b =>
                {
                    b.Property<int>("EspeciesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductosId")
                        .HasColumnType("int");

                    b.HasKey("EspeciesId", "ProductosId");

                    b.HasIndex("ProductosId");

                    b.ToTable("ProductoEspecie", (string)null);
                });

            modelBuilder.Entity("ProductoSugerido", b =>
                {
                    b.Property<int>("ProductoSugeridoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("ProductoSugeridoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoSugerido");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("EfectivoContado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FondoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondicionIva")
                        .HasColumnType("int");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LimiteCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazonSocialONombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SinLimite")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualizadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("LimiteCreditoPorDefecto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActualizadoPorUsuarioId");

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.CuentaCorriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("CuentasCorrientes");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.DetalleDevolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("DevolucionId")
                        .HasColumnType("int");

                    b.Property<int>("ItemPedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevolucionId");

                    b.HasIndex("ItemPedidoId");

                    b.ToTable("DetallesDevolucion");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Devolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaReintegro")
                        .HasColumnType("int");

                    b.Property<int>("MotivoDevolucionId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotivoDevolucionId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.EscalonPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("EscalonesDePrecio");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminoColoquial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CaeVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClienteCondicionIvaSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("ClienteCuitSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteRazonSocialSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DevolucionId")
                        .HasColumnType("int");

                    b.Property<int?>("FacturaOriginalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("PuntoDeVenta")
                        .HasColumnType("int");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevolucionId")
                        .IsUnique()
                        .HasFilter("[DevolucionId] IS NOT NULL");

                    b.HasIndex("FacturaOriginalId");

                    b.HasIndex("PedidoId")
                        .IsUnique()
                        .HasFilter("[PedidoId] IS NOT NULL");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.FranjaHoraria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("HoraDesde")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraHasta")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("FranjasHorarias");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.HistorialEstadoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialesDeEstadoPedido");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.HistorialPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModificadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.HasIndex("ProductoId");

                    b.ToTable("HistorialesDePrecio");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.ImagenProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ImagenesProducto");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsPedido");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.MotivoDevolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MotivosDevolucion");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.MovimientoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaCorrienteId")
                        .HasColumnType("int");

                    b.Property<int?>("DevolucionId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAprobacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PagoId")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuentaCorrienteId");

                    b.HasIndex("DevolucionId")
                        .IsUnique()
                        .HasFilter("[DevolucionId] IS NOT NULL");

                    b.HasIndex("PagoId")
                        .IsUnique()
                        .HasFilter("[PagoId] IS NOT NULL");

                    b.HasIndex("PedidoId")
                        .IsUnique()
                        .HasFilter("[PedidoId] IS NOT NULL");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosCuenta");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReglaCampaniaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ReglaCampaniaId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CajaId")
                        .HasColumnType("int");

                    b.Property<int?>("DevolucionId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("MedioDePago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("Sentido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("DevolucionId")
                        .IsUnique()
                        .HasFilter("[DevolucionId] IS NOT NULL");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRetiro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FranjaHorariaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FranjaHorariaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Plantel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEl")
                        .HasColumnType("datetime2");

                    b.Property<int>("CantidadCabezas")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EspecieId")
                        .HasColumnType("int");

                    b.Property<int>("TipoProduccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EspecieId");

                    b.ToTable("Planteles");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("AlicuotaIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDeBarras")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<string>("UnidadDeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoDeBarras")
                        .IsUnique()
                        .HasFilter("[CodigoDeBarras] IS NOT NULL");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.ReglaCampania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("DiaInicio")
                        .HasColumnType("int");

                    b.Property<int?>("EspecieId")
                        .HasColumnType("int");

                    b.Property<int?>("IntervaloDias")
                        .HasColumnType("int");

                    b.Property<string>("MensajePlantilla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MesInicio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDisparo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EspecieId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ReglasCampania");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ClienteUsuario", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EspecieProducto", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Especie", null)
                        .WithMany()
                        .HasForeignKey("EspeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductoSugerido", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoSugeridoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Caja", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Usuario", "Usuario")
                        .WithMany("CajasGestionadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Configuracion", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Usuario", "ActualizadoPor")
                        .WithMany("ConfiguracionesActualizadas")
                        .HasForeignKey("ActualizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActualizadoPor");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.CuentaCorriente", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Cliente", "Cliente")
                        .WithOne("CuentaCorriente")
                        .HasForeignKey("ProveeduriaGanadera.Domain.Entities.CuentaCorriente", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.DetalleDevolucion", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Devolucion", "Devolucion")
                        .WithMany("Detalles")
                        .HasForeignKey("DevolucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.ItemPedido", "ItemPedido")
                        .WithMany("DetallesDevueltos")
                        .HasForeignKey("ItemPedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Devolucion");

                    b.Navigation("ItemPedido");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Devolucion", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.MotivoDevolucion", "MotivoDevolucion")
                        .WithMany("Devoluciones")
                        .HasForeignKey("MotivoDevolucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Devoluciones")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Usuario", "Usuario")
                        .WithMany("DevolucionesGestionadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotivoDevolucion");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.EscalonPrecio", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Producto", "Producto")
                        .WithMany("EscalonesDePrecio")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Factura", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Devolucion", "Devolucion")
                        .WithOne("NotaDeCredito")
                        .HasForeignKey("ProveeduriaGanadera.Domain.Entities.Factura", "DevolucionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Factura", "FacturaOriginal")
                        .WithMany()
                        .HasForeignKey("FacturaOriginalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Pedido", "Pedido")
                        .WithOne("Factura")
                        .HasForeignKey("ProveeduriaGanadera.Domain.Entities.Factura", "PedidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Devolucion");

                    b.Navigation("FacturaOriginal");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.HistorialEstadoPedido", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Pedido", "Pedido")
                        .WithMany("HistorialDeEstados")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Usuario", "Usuario")
                        .WithMany("CambiosDeEstadoPedido")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.HistorialPrecio", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Usuario", "ModificadoPor")
                        .WithMany("CambiosDePrecio")
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Producto", "Producto")
                        .WithMany("HistorialDePrecios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModificadoPor");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.ImagenProducto", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Producto", "Producto")
                        .WithMany("Imagenes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Producto", "Producto")
                        .WithMany("ItemsDePedido")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Lote", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.MovimientoCuenta", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.CuentaCorriente", "CuentaCorriente")
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaCorrienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Devolucion", "Devolucion")
                        .WithOne("MovimientoCuentaGenerado")
                        .HasForeignKey("ProveeduriaGanadera.Domain.Entities.MovimientoCuenta", "DevolucionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Pago", "Pago")
                        .WithOne("MovimientoCuenta")
                        .HasForeignKey("ProveeduriaGanadera.Domain.Entities.MovimientoCuenta", "PagoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Pedido", "Pedido")
                        .WithOne("MovimientoCuenta")
                        .HasForeignKey("ProveeduriaGanadera.Domain.Entities.MovimientoCuenta", "PedidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MovimientosGestionados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuentaCorriente");

                    b.Navigation("Devolucion");

                    b.Navigation("Pago");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Notificaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.ReglaCampania", "ReglaCampania")
                        .WithMany("Notificaciones")
                        .HasForeignKey("ReglaCampaniaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("ReglaCampania");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Pago", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Caja", "Caja")
                        .WithMany("Pagos")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Devolucion", "Devolucion")
                        .WithOne("PagoGenerado")
                        .HasForeignKey("ProveeduriaGanadera.Domain.Entities.Pago", "DevolucionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("Devolucion");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.FranjaHoraria", "FranjaHoraria")
                        .WithMany("Pedidos")
                        .HasForeignKey("FranjaHorariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PedidosRealizados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("FranjaHoraria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Plantel", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Planteles")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Especie", "Especie")
                        .WithMany("Planteles")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Producto", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.ReglaCampania", b =>
                {
                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Reglas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Especie", "Especie")
                        .WithMany("Reglas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProveeduriaGanadera.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ReglasGestionadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Especie");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Caja", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("CuentaCorriente");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pedidos");

                    b.Navigation("Planteles");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.CuentaCorriente", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Devolucion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("MovimientoCuentaGenerado");

                    b.Navigation("NotaDeCredito");

                    b.Navigation("PagoGenerado");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Especie", b =>
                {
                    b.Navigation("Planteles");

                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.FranjaHoraria", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.ItemPedido", b =>
                {
                    b.Navigation("DetallesDevueltos");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.MotivoDevolucion", b =>
                {
                    b.Navigation("Devoluciones");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Pago", b =>
                {
                    b.Navigation("MovimientoCuenta");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Devoluciones");

                    b.Navigation("Factura");

                    b.Navigation("HistorialDeEstados");

                    b.Navigation("Items");

                    b.Navigation("MovimientoCuenta");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Producto", b =>
                {
                    b.Navigation("EscalonesDePrecio");

                    b.Navigation("HistorialDePrecios");

                    b.Navigation("Imagenes");

                    b.Navigation("ItemsDePedido");

                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.ReglaCampania", b =>
                {
                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("ProveeduriaGanadera.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("CajasGestionadas");

                    b.Navigation("CambiosDeEstadoPedido");

                    b.Navigation("CambiosDePrecio");

                    b.Navigation("ConfiguracionesActualizadas");

                    b.Navigation("DevolucionesGestionadas");

                    b.Navigation("MovimientosGestionados");

                    b.Navigation("PedidosRealizados");

                    b.Navigation("ReglasGestionadas");
                });
#pragma warning restore 612, 618
        }
    }
}
